name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with: 
          who-to-greet: Jeff 
      - name: Log Greeting Time
        run: echo "${{ steps.greet.output.time}}"

