name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node version
        run: node -v
      - name: step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script 
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/bin/chmod
          args: ./script.sh 
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
# working with a docker container
    # services:
    #   app:
    #     image: alialaa17/node-api
    #     ports:
    #       - 3001:3000
    #   mongo:
    #     image: mongo
    #     ports:
    #       - "27017:27017"
    # steps:
    #   - name: post a user 





